name: Batch Publish Release

on:
  push:
    tags: [ 'bp/*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: "release"
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install Nats Server
        run: |
          pkill -9 nats-server 2>/dev/null || true
          mkdir -p ~/.local/bin
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go build -o ~/.local/bin/nats-server
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v4
      - name: Compile and Test
        run: |
          pushd batch-publish
          chmod +x gradlew && ./gradlew clean test
          popd
      - name: Verify, Sign and Publish Release
        run: |
          pushd batch-publish
          ./gradlew -i publishToSonatype closeAndReleaseSonatypeStagingRepository
          popd
      - name: Clean up
        if: always()
        run: pkill -9 nats-server 2>/dev/null || true
