name: Counter Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'counters/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: counters
    secrets: inherit
