name: Counter Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'counters/**'

jobs:
  build:
    uses: ./.github/workflows/workflow-main.yml
    with:
      project-dir: counters
    secrets: inherit
