name: Counter Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'counters/**'

jobs:
  build:
    uses: ./.github/workflows/workflow-pr.yml
    with:
      project-dir: counters
    secrets: inherit
