name: Partitioned Consumer Groups Release

on:
  push:
    tags: [ 'pcg/*' ]

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-release.yml@main
    with:
      project-dir: pcgroups
    secrets: inherit
