name: Partitioned Consumer Groups Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'pcgroups/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-pr.yml@main
    with:
      project-dir: pcgroups
    secrets: inherit
