name: Partitioned Consumer Groups Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'pcgroups/**'

jobs:
  build:
    uses: ./.github/workflows/workflow-pr.yml
    with:
      project-dir: pcgroups
    secrets: inherit
