name: Partitioned Consumer Groups Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'pcgroups/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: pcgroups
    secrets: inherit
