name: Scheduled Message Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'schedule-message/**'

jobs:
  build:
    uses: ./.github/workflows/workflow-main.yml
    with:
      project-dir: schedule-message
    secrets: inherit
