name: Scheduled Message Main Snapshot

on:
  push:
    branches:
      - main
    paths:
      - 'schedule-message/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-main.yml@main
    with:
      project-dir: schedule-message
    secrets: inherit
