name: Scheduled Message Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'schedule-message/**'

jobs:
  build:
    uses: ./.github/workflows/workflow-pr.yml
    with:
      project-dir: schedule-message
    secrets: inherit
