name: Scheduled Message Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'schedule-message/**'

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-pr.yml@main
    with:
      project-dir: schedule-message
    secrets: inherit
