name: Scheduled Message Release

on:
  push:
    tags: [ 'sm/*' ]

jobs:
  build:
    uses: synadia-io/workflows/.github/workflows/java-standard-release.yml@main
    with:
      project-dir: schedule-message
    secrets: inherit
