name: Scheduled Message Release

on:
  push:
    tags: [ 'sm/*' ]

jobs:
  build:
    uses: ./.github/workflows/workflow-release.yml
    with:
      project-dir: schedule-message
    secrets: inherit
